<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <PackageId>FS.Skia.UI</PackageId>
    <AssemblyName>FS.Skia.UI</AssemblyName>
    <Version>0.1.25-preview.1</Version>
    <Title>FS.Skia.UI</Title>
    <Description>Elmish-only Vulkan desktop viewer primitives for F# and SkiaSharp.</Description>
    <PackageTags>fsharp;elmish;skia;vulkan;desktop</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="InternalsVisibleTo.fs" />
    <Compile Include="VulkanResources.fsi" />
    <Compile Include="VulkanResources.fs" />
    <Compile Include="VulkanStartup.fsi" />
    <Compile Include="VulkanStartup.fs" />
    <Compile Include="Library.fsi" />
    <Compile Include="Library.fs" />
    <Compile Include="KeyboardInput.fsi" />
    <Compile Include="KeyboardInput.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Elmish" />
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="Silk.NET.Windowing.Extensions" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

</Project>
