// Generate docs/controls-contrast.md — a WCAG contrast reference for the theme colors the
// FS.Skia.UI.Controls docs render with, computed by the shipped FS.Skia.UI.Color package
// (dogfooding feature 083). Reads the DTCG single source (the same colors that feed
// DesignTokens.Light/Dark and therefore every control preview) and runs Contrast.check over
// them. Pure managed — only the Scene + Color assemblies; no native/render path.
//
// Run:  dotnet fsi scripts/controls-docs-contrast.fsx

#r "/home/developer/projects/FS-Skia-UI/src/Scene/bin/Debug/net10.0/FS.Skia.UI.Scene.dll"
#r "/home/developer/projects/FS-Skia-UI/src/Color/bin/Debug/net10.0/FS.Skia.UI.Color.dll"

open System.IO
open System.Text
open System.Text.Json
open FS.Skia.UI.Scene
open FS.Skia.UI.Color

let repoRoot = "/home/developer/projects/FS-Skia-UI"
let tokensPath = Path.Combine(repoRoot, "src/Controls/design-tokens.tokens.json")

// --- read the DTCG colour tokens (alias-resolved) the controls render with -------------------
let doc = JsonDocument.Parse(File.ReadAllText tokensPath)

let colorRoles = [ "foreground"; "background"; "accent"; "danger"; "muted" ]

let parseHex (raw: string) =
    let hex = raw.TrimStart('#')
    let b i = System.Convert.ToByte(hex.Substring(i, 2), 16)
    Colors.rgba (b 0) (b 2) (b 4) (b 6)

let rec resolveValue (theme: JsonElement) (themeName: string) (token: string) =
    let raw = theme.GetProperty(token).GetProperty("$value").GetString()
    if raw.StartsWith "{" then
        // DTCG alias "{group.token}" — resolve against the named group.
        let inner = raw.Trim('{', '}')
        let parts = inner.Split('.')
        let grp = doc.RootElement.GetProperty(parts.[0])
        resolveValue grp parts.[0] parts.[1]
    else
        raw

let themeColors (themeName: string) =
    let theme = doc.RootElement.GetProperty(themeName)
    colorRoles |> List.map (fun r -> r, parseHex (resolveValue theme themeName r))

// --- render helpers --------------------------------------------------------------------------
let verdictName v =
    match v with
    | Aaa -> "AAA" | Aa -> "AA" | AaLarge -> "AA-Large"
    | Fail -> "Fail" | Exempt -> "Exempt" | Indeterminate -> "Indeterminate"

let hex (c: Color) = sprintf "#%02x%02x%02x%02x" c.Red c.Green c.Blue c.Alpha

let sb = StringBuilder()
let line (s: string) = sb.AppendLine s |> ignore

line "# Theme contrast reference"
line ""
line "WCAG 2.x contrast for the theme colours every FS.Skia.UI.Controls preview renders with,"
line "computed by the shipped **FS.Skia.UI.Color** package (`Contrast.check` / `Contrast.ratio`)"
line "over the DTCG single source (`src/Controls/design-tokens.tokens.json`). The controls docs"
line "render against `DesignTokens.Light`; the dark theme is included for completeness. Text"
line "pairings target AA body text (≥ 4.5:1); non-text/UI use WCAG 1.4.11 (≥ 3:1)."
line ""
line "_Generated by `scripts/controls-docs-contrast.fsx` — do not hand-edit._"

for themeName in [ "light"; "dark" ] do
    let colors = themeColors themeName
    let bg = colors |> List.find (fun (n, _) -> n = "background") |> snd

    line ""
    line (sprintf "## %s theme" themeName)
    line ""
    line "### Foreground roles over the surface background (role Text)"
    line ""
    line "| Foreground role | Foreground | Background | Ratio | Verdict | AA (≥4.5) |"
    line "|-----------------|------------|------------|-------|---------|-----------|"
    for (name, c) in colors do
        if name <> "background" then
            let r = Contrast.check Text bg c
            line (sprintf "| %s | %s | %s | %.2f:1 | %s | %s |"
                    name (hex c) (hex bg) r.Ratio (verdictName r.Verdict)
                    (if r.Ratio >= 4.5 then "yes" else "**no**"))

    line ""
    line "### Full pairing matrix — any role as foreground over any role as background (role Text, ratio)"
    line ""
    line ("| fg \\ bg | " + (colors |> List.map fst |> String.concat " | ") + " |")
    line ("|" + String.replicate (List.length colors + 1) "---|")
    for (fgName, fg) in colors do
        let cells =
            colors
            |> List.map (fun (_, bgc) -> sprintf "%.2f" (Contrast.ratio fg bgc))
            |> String.concat " | "
        line (sprintf "| %s | %s |" fgName cells)

let outPath = Path.Combine(repoRoot, "docs/controls-contrast.md")
File.WriteAllText(outPath, sb.ToString())
printfn "wrote %s" outPath
