<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Scene\Scene.fsproj" />
    <ProjectReference Include="..\..\src\Layout\Layout.fsproj" />
    <ProjectReference Include="..\..\src\KeyboardInput\KeyboardInput.fsproj" />
    <ProjectReference Include="..\..\src\Controls\Controls.fsproj" />
    <ProjectReference Include="..\..\src\Controls.Elmish\Controls.Elmish.fsproj" />
  </ItemGroup>

</Project>
